_includes/panel.html
_layouts/post.html
tabs/categories.md
tabs/tags.md

I found that links did not work if I set 'C#' as either category, sub-category or tag. The changes in this pull request fixed the problem with links within category tab, tags tab, in top and bottom section of posts, and with tags in right-side panel.

Allow special characters in categories and tags

---

assets/css/_dark/dark-main.scss
assets/css/_dark/dark-syntax.scss

Hi @cotes2020 , I'm about to implement this feature in my fork and figured it might be useful for others as well.
**This PR allows you to switch between dark and light scheme** with a body class. The implementation detail is left on developers, but this is an example of how to implement such switch:
```
<button
class="color-scheme-dark-hidden"
onclick="
$('body')
.removeClass('color-scheme-light')
.addClass('color-scheme-dark')
">Dark scheme</button>
<button
class="color-scheme-light-hidden"
onclick="
$('body')
.removeClass('color-scheme-dark')
.addClass('color-scheme-light')
">Light scheme</button>
```

[Feature] Allow toggling of dark scheme + Display elements based on color scheme

---

assets/css/main.scss

Adds word break on search result page preamble, this bug is caused when using code markdown early in a post a can be seen in the screenshot below.

Fix to search result overflow

---

_data/contact.yml

In `_data/contact.yml` arbritary contact links can be put and associated with an icon. font awesome ships a mastodon icon, so an example was added to the file. It will only show if the url-field is filled, as explained in the comment.
Fixes #81 
... which unit tests? :)

add example for mastodon contact

---

_includes/sidebar.html

Clicking on the email 'social button' in the sidebar opens a blank page as wel as triggering my email client. This small change to the javascript triggering the email client doesn't create a blank page.
Remediates the issue described in [this stack overflow post]( https://stackoverflow.com/questions/21461589/javascript-mailto-using-window-open#32675594), using the recommended fix.
- Browerser type & version: Mozilla Firefox 81.0.1
- Operating system: Linux
- Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
- Jekyll version: v2.0

Improve email javascript in sidebar

---

_posts/2019-08-08-write-a-new-post.md

Fix instruction on where to host posts. (ie) the `/posts/` should hold all docs. not `/post`
Markdown change
- Browerser type & version:
- Bundler version:
- Ruby version:

Fix the dir name for hosting posts

---

assets/css/_colors/dark-typography.scss

"inherit" was spelled wrong in the dark typography scss.
Not tested. Seems straightforward.

fixed typo in dark typography

---

_layouts/post.html
_posts/2019-08-08-write-a-new-post.md

e.g. Fixes #(issue)
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Browser type & version: Safari v14.0.1
- Operating system: MacOS Catalina v10.15.7
- Bundler version: 2.2.7
- Ruby version: 2.5.5p15
- Jekyll version: 4.2.0

Add image alt attribute to the from the top of the post contents

---

_includes/mode-toggle.html
_includes/sidebar.html

This is a fix for accessibility bug
- if you press tab then the focus doesn't reach dark mode toggle button
- After focus should reach the dark mode toggle button, pressing enter button should change the theme of website
e.g. Fixes #(issue)
-->
- Operating system: Windows
- Ruby version: 2.7.4p191 
- Bundler version:  2.2.30

Accessibility Bug Fix: Tab focus doesn't reach Dark mode toggle button

---

_data/locales/ko-KR.yml

Add Korean locales

---

_includes/refactor-content.html
_sass/addon/module.scss

`<a>` tags in headings are set to apply the style of `%anchor` in `module.scss` and `common.scss`. Therefore, if I put a link in a heading, the link will have the same style as the anchor, which means that the font size becomes smaller and the link will not be displayed unless I hover the mouse over it.
For example, 
```
```
in a markdown file is displayed like this.
My suggestion is to set an `anchor` class for the `<a>` tag of the anchor and apply style settings to the `anchor` class, not to the `a` tag.
- Browser type & version: Google Chrome 96.0.4664.110
- Operating system: Windows 10 21H1 + WSL (18.04.1 LTS)
- Ruby version: 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
- Bundler version:  2.2.15

Bug Fix: Link in a heading is rendered as an anchor and becomes invisible.

---

_data/locales/en.yml

This is a very minor wording fix/suggestion, but I think that it is more grammatically correct to say `Recently Updated` vs. `Recent Update`. `Recent Update`, to me, implies singularity whereas `Recently Updated` could imply single or multiple updated post(s).
I think `Recently Updates` could also work here, depending on preference, since it matches `Tags` and `Table of Contents`.  But the problem would be if there are only 1 recently updated post, it would be dramatically incorrect. 
Really splitting hairs here, but I made the change on my blog so thought I would contribute back. 
Feel free to reject if you disagree! 🙂
- Browser type & version: `Brave (chromium) 1.33.106`
- Operating system: `macOS 11.6.3`
- Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`
- …

update english locales for recently updated posts

---

_includes/head.html
_includes/js-selector.html

I'm in the EU, so I have to turn off Google Analytics entirely to avoid legal issues. I noticed that the Google Analytics script was still being loaded even though I hadn't changed `google_analytics.id` from the empty string in `_config.yml`.
I'm not sure if the first part of the conditions is still needed, since I don't know the Liquid templating language.
I suspect it's necessary in case someone comments out that part of the configuration.
This is a bit of a "maybe you can use this" PR, since I'm maintaining my fork separately just for my page (because I customised a number of things outside the configuration files) and won't necessarily upgrade to the next version of Chirpy.
(I'm on Windows, which is probably (part of) why this doesn't work for me. I did use bash.)
- Browser type & …

Don't include Google Analytics scripts without analytics id

---

_data/share.yml

This is regarding https://github.com/cotes2020/jekyll-theme-chirpy/issues/488
This commit fixes the broken telegram sharing function by using the latest link as per official telegram documentation.
https://core.telegram.org/widgets/share#custom-buttons
- Browser type & version: Safari, Chrome
- Operating system: iOS 15.1
- Ruby version: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
- Gem version: 3.0.3.1
- Bundler version: Bundler version 2.3.5
- Jekyll version: * jekyll (4.2.1)

changed telegram share link api as per documentation

---

_includes/head.html
_includes/post-sharing.html
_layouts/default.html

Theme toggle JS code was in between head and body tags (invalid placement), now moved to the head.
Share links now use `url_encode` instead of `escape` since the latter doesn't encode spaces and other special characters like '&' are encoded as HTML entities instead of % values (a post title containing an '&' will be cut short).
- Browser type & version: Firefox 97.0.1
- Ruby version: 2.7.4p191
- Bundler version: 2.3.8

Fix script location and URL encode share links

---

assets/js/data/search.json

Invalid JSON is generated when a post contains tab characters since the `remove_chars` filter plugin is missing ( https://github.com/christian-fei/Simple-Jekyll-Search/tree/master/example/_plugins ). Use `jsonify` instead.
Relates to https://github.com/cotes2020/jekyll-theme-chirpy/pull/475
Even if the text editor has been configured to use spaces instead of tabs, Rouge syntax highlighter will generate tabs in its tables.
- Browser type & version: Firefox 97.0.1
- Ruby version: 2.7.4p191
- Bundler version: 2.3.8
- Jekyll version:  4.2.1

Use jsonify to generate valid JSON

---

_data/locales/pt-BR.yml

Add support for brazilian portuguese.

feat: add pt-BR support to locales

---

tools/deploy.sh

When using the theme starter, which uses a git submodule, assets loaded from that submodule are "untracked" files in the pages branch working tree. The build can fail at this line due to Git, saying "the following untracked working tree files would be overwritten by checkout".
Adding `checkout -f` forces the checkout, overwriting all files. The other deploy steps then take over and rewrite the files as needed.
- Failing build with the old version: https://github.com/GriceTurrble/galenrice.com/runs/5790580358?check_suite_focus=true
- Passing build with the new: https://github.com/GriceTurrble/galenrice.com/runs/5790781891?check_suite_focus=true

fix: force checkout of Pages branch

---

_sass/addon/commons.scss

Currently, long equations rendered by MathJax tend to overflow the post content onto the right side navigational toc and on phones, they get completely cut off. PR introduces a horizontal scroll for along equations.  
Fixes #543 
I specified a long equation detailed below
```markdown
$$
(a + b)^3 = {3 \choose 0} a^3 b^0 + {3 \choose 1} a^2 b^1 + {3 \choose 2} a^1 b^2 + {3 \choose 0} a^0 b^3 + 0 \left ({3 \choose 0} a^3 b^0 + {3 \choose 1} a^2 b^1 + {3 \choose 2} a^1 b^2 + {3 \choose 0} a^0 b^3 \right )
$$
```
This equation currently runs over the navigation toc in the browser and gets completely cut off on the phone as described in the feature request: #543 
Post making the changes in this PR, a disappearing horizontal scroll appears for long equation. 
- Browser type & version: Safari …

feat: horizontal scroll for long equations

---

_includes/head.html
_includes/js-selector.html
_includes/mermaid.html
_includes/search-loader.html
_includes/toc.html

Fixes: Some assets is 404 when baseurl isn't empty and assets is 'self_host'
```yml
baseurl: /i-am-not-empty
assets:
self_host: true
enabled:      # boolean, keep empty means false
env:          # [development|production]
```
- Browser type & version: chrome
- Operating system: win10
- Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt] 
- Bundler version: Bundler version 2.3.14 
- Jekyll version:   * jekyll (4.2.2)

 fix: assets 404 when baseurl isn't empty and assets is 'self_host'

---

_data/locales/en.yml

Fixes a minor typo in the English locale.
- Browser type & version: Firefox 101.0
- Ruby version: 2.7.3
- Bundler version: 2.2.20

Fix typo in English locale file

---

_data/locales/hu-HU.yml

In the 'mighty' hungarian language we don't use plurals after numbers. This will fix it on the Categories page.

fix: typo in Hungarian locale file

---

_posts/2019-08-08-write-a-new-post.md

Adding a note in the writing a post markdown to make it clear for those upgrading themes that they will need to update their preview images.
See #625

adding a note about preview images and 5.2.0

---

_includes/refactor-content.html

If you have an element included inside a header, for an example:
```markdown
```
You will find that the element `var` is set to right margin:
The bug arises from the code here:
```liquid
{% assign left = left | replace: '">', '"><span class="mr-2">' | append: '</span>' %}
```
To fix it, we can use `replace_first` instead of `replace`:
```liquid
{% assign left = left | replace_first: '">', '"><span class="mr-2">' | append: '</span>' %}
```
- Browser type & version: Google Chrome 103.0.5060.114
- Operating system: Ubuntu 20.04
- Ruby version: 2.7.0p0
- Bundler version: 2.3.13

fix: wrong margin inside headers

---

_sass/layout/post.scss

When users want to use Linkedin and Weibo for sharing by uncommenting them in share.yml, the LinkedIn icon doesn't have its color, whereas Weibo has its color. Turned out that Linkedin's icon color is missing in post.scss.
Solution:
Add Linkedin color in post.scss, the color is based on LinkedIn's official brand color:
https://brand.linkedin.com/content/brand/global/en_us/index/visual-identity/color-palettes
- Browser type & version: Google Chrome Version 104.0.5112.102 (Official Build) (64-bit)
- Operating system: Windows 11
- Ruby version: ruby 3.1.2p20
- Bundler version: Bundler version 2.3.21
- Jekyll version: jekyll (4.2.2)

fix: linkedin icon color doesn't exist when user use linkedin in share.yml

---

_layouts/page.html
_layouts/post.html
_sass/layout/home.scss

Corrected the spelling of the word `panel` for consistency.
- Browser type & version: Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)
- Ruby version: 3.1.2p20 
- Bundler version: 2.3.21 

fix: correct spelling of `panel`

---

_layouts/post.html
_posts/2019-08-08-write-a-new-post.md

This PR changes the post layout in order to support multiple authors in one post. #675 
You enter the authors' id in post YAML block as a list, the page renders co-authors separated by comma.
- Browser type & version: Safari 15, Chrome 104
- Operating system: macOS 12
- Ruby version: 2.6
- Bundler version: 1.17

feat: co-author in one post

---

_sass/addon/commons.scss

Closes https://github.com/cotes2020/jekyll-theme-chirpy/issues/702
Removing extra padding in nested lists
From:
To:
This reflects more of how it looks like in GitHub:
- Coffee
- Tea
* Black tea
* Green tea
- Milk
(Depending on how you look at this, could be bug, could be feature 🤷 )
Tested with latest `master` branch
- Browser type & version: Chrome latest
- Operating system: macOS latest
- Ruby version:  ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
- Bundler version:  Bundler version 2.3.7
- Jekyll version:  jekyll (4.2.2)

Removing extra padding in nested lists

---

_config.yml
_includes/comments/giscus.html

Add `reactions_enabled` parameter for giscus to allow users to enable/disable reactions.

chore(giscus): Add reactions_enabled parameter

---

_sass/addon/commons.scss

`.post-content { >ol, >ul ...` prevents the styles from being applied to the lists inside blockquote. 
- Browser type & version: Google Chrome 107.0.5304.68
- Operating system: Ubuntu 22.04
- Ruby version: 3.0.2p107
- Bundler version: 2.3.5

perf(css): apply styles to lists inside blockquote

---

_data/contact.yml
_includes/sidebar.html

This will enable verification with Mastodon by including the `rel="me"` attribute.
https://docs.joinmastodon.org/user/profile/#verification
- ~~[ ] I have run `bash ./tools/test.sh` (at the root of the project) locally and passed~~ tested via https://github.com/kendaleiv/jekyll-theme-chirpy/pull/1
- Browser type & version: Edge 108
- Ruby version: ruby 3.1.2p20
- Bundler version: 2.3.7
- Jekyll version: 4.3.1

feat: add rel="me" to Mastodon sidebar contact links for verification

---

.editorconfig

Option `trim_trailing_whitespace` in `.editorconfig` is switched on globally which is wrong because two trailing spaces has special meaning in `md` files.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have tested this feature in the browser
- Operating system: Ubuntu Linux
- Ruby version: 3.0.2
- Bundler version: 2.3.5
- Jekyll version: 4.3.1

Do not trim whitespaces in md

---

_includes/comments/disqus.html

Disqus can't be loaded due to an uncaught syntax error: Identifier 'modeToggle' has already been declared at elsewhere. The solution is to use another name.
- Browser type & version: Chrome
- Operating system: MacOS

Solve a bug in Disqus

---

_data/locales/zh-TW.yml

As titled.
- Browser type & version: *unrelated*
- Operating system: Windows 10 Pro (build 21H2) with MinGW64
- Ruby version: 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]
- Bundler version: Bundler version 2.3.26
- Jekyll version: jekyll (4.3.2)

feat(i18n): add Traditional Chinese (Taiwan) localization file

---

_data/locales/sv-SE.yml

Added the Swedish Language support in the jekyll-theme-chirpy via the folder: _data/locales/sv-SE.yml
- Browser type & version: Firefox 11.0.1 , Safari 16.4, Chrome 111.0
- Operating system: MacOS 12.6.4
- Ruby version:  3.1.2
- Bundler version: 2.4.10
- Jekyll version:  4.3.2

feat(i18n): added Swedish localization file

---

assets/feed.xml

It might cause a syntax error if the `post.title` contains double quotes. One of the solutions is using the `escape` filter.

Fix a bug in feed.xml

---

_sass/addon/commons.scss
_sass/addon/module.scss
_sass/addon/variables.scss
_sass/jekyll-theme-chirpy.scss

Move the font family and font size of the body and headings into `variables.scss` so that making them be more easily customizable for users.

feat: make fonts customizable

---

tools/init

When a fork chooses to only copy the `master` branch, initialization tool will be interrupted due to the lack of git-tag information.
Run the init-tool with single branch.

perf(tools): avoid initialization interruption in single branch forks

---

_includes/head.html
_includes/metadata-hook.html

This new feature allows users to define custom metadata in the `<head>` without overriding the whole `head.html`. They just need to put their metadata into `custom-head.html`, then the metadata would be automatically included into the `<head>`.

feat: allow users to define custom metadata

---

_layouts/post.html

There is the current (although somewhat hidden) ability to set "last_modified_at: " in the front matter of a post to use a user-specified datetime instead of the built in logic.
New feature in post.html:  if the modified date time matches the date of the post, then don't show "Updated xxxx"
This is useful when bringing in old posts and you don't want the 'updated xxx' to display today's date on a 3 year old post.
One-liner improvement to post.html
Validation:
3 types of blog posts:
1) Front matter without `last_modified_at` specified  (unchanged: current display logic occurs)
2) Front matter with `last_modified_at` not matching `date` (unchanged: display logic uses specified value)
3) Front matter with `last_modified_at` matching `date`  (new: Updated does not display)

Minor new feature:  For blog posts, the "Updated xxxx" datetime is displayed next to the Posted datetime even if not desired.

---

_includes/refactor-content.html

Image links have a shimmer effect when loading, but this effect was accidentally lost in the development of _v6.0.0_ (97b8dfe). 
This commit brings it back up again.

Resume the shimmer effect of image links

---

_includes/post-paginator.html
_layouts/page.html
_sass/addon/commons.scss
_sass/layout/home.scss

Restore the margin at the bottom of the main content area that was lost in _v6.0.0_.
In a way, this is a fix for d81f836
Commit d81f836

Fix the margin at the bottom of the main content area

---

_sass/addon/commons.scss

In _v6.0.0_, some unused SCSS code was left behind when the top bar collapsing feature was deprecated.

Remove dead SCSS code

---

tools/release

Tag on `production` branch instead of `master`, which is more in line with the GitLab Flow standard.

Improve the git-tagging strategy

---

_javascript/modules/components/back-to-top.js
_layouts/default.html

The current "back to top" button is built by `<a>` tag, it would be more appropriate to replace it with the `<button>` tag.

refactor: improve JS/HTML for button back2top

---

_includes/head.html
_includes/refactor-content.html
_includes/related-posts.html
_includes/search-results.html
_layouts/archives.html
_layouts/categories.html
_layouts/category.html
_layouts/default.html
_layouts/home.html
_layouts/page.html
_layouts/post.html
_layouts/tag.html
assets/feed.xml
assets/js/data/search.json
jekyll-theme-chirpy.gemspec

Use `jekyll-include-cache` plugin to reduce build time

---

_sass/addon/commons.scss

H5 search cancel text arranges vertically when lang switched to zh-CN. I think it is a bug.
- follow the [contribution doc](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md)，fork the project and clone it locally
- install deps
- change`_config.yml`: `lang: en` to `lang: zh-CN`
- run `npm run build && bundle exec jekyll serve`
- view in chrome devtool with mobile mode, click search icon, you will see "取消" arranging vertically at right side
- with this commit, reproduce above steps and get the correct render result.

The CJK characters of the "Search Cancel" button will wrap

---

_layouts/home.html
_layouts/post.html

When specifying a preview image in a post,  
if you specify a value of < or > for `alt`, the image will not display properly because it encroaches on the HTML tag range.
1. Create a new post.
2. In the post properties, write image.alt to contain < or >, as follows
- example
```yml
image:
path: /commons/devices-mockup.png
alt: get device image -> show mockup
```
- At Home (root path)
- At Post

fix: image preview display error when image.alt includes '<' or '>'

---

_includes/related-posts.html

If the site has a large number of posts, and a lot of metadata (`categories` and `tags` from posts), then rendering the `_includes/related-posts.html` will be a bottleneck in build time.
With 1082 posts, 94 categories, and 26 tags, on a machine configured with Intel Core i7 CPU and 16GB RAM, the site's build time details are as follows:
```
Build Process Summary:
| PHASE    |     TIME |
+----------+----------+
| RESET    |   0.0003 |
| READ     |  34.1979 |
| GENERATE |   0.1318 |
| RENDER   | 123.6652 |
| CLEANUP  |   0.1728 |
| WRITE    |   0.7328 |
Site Render Stats:
| Filename                                                                                  | Count |     Bytes |    Time |
+-------------------------------------------------------------------------------------------+------ …
```

Speed up the Jekyll build times for large sites

---

_includes/comments/disqus.html
_sass/addon/commons.scss
_sass/addon/variables.scss
_sass/layout/post.scss

Keeps the margin of the elements in the tail area consistent regardless of the number of siblings, or if a `<script>` is inserted.

perf(layout): improve margins for tail block

---

_layouts/default.html
_sass/addon/commons.scss

If the post content height is smaller than the panel, there will be a large blank space between the bottom of the post and "Further Reading" section.

Optimize the main block height calculation

---

_sass/addon/commons.scss
_sass/addon/module.scss

`<sup>` and `<footnote>` are highlighted when in `:target` state, but this feature has been missing since `v6.1.0` due to an oversight in development.

Resume target highlighting for superscripts and footnotes

---

_layouts/home.html

Assuming that there are two articles on the homepage, and the higher one has an LQIP preview image set up, while the lower one has a preview image without an LQIP, it will be accidentally contaminated by the previous one's LQIP.
This PR fixes the above issue.

Avoid LQIP dirty data from the homepage being passed on to the next post

---

_sass/addon/commons.scss

When the preview image doesn't load fast enough, the image area goes blank for a short while.
The background of the preview image is blank, and when the LQIP appears quickly, it causes visual flickering.
https://github.com/cotes2020/jekyll-theme-chirpy/assets/11371340/a004213f-440a-4112-95c2-f2d044332010
Rendering the background color before the image is loaded acts as a placeholder and makes it visually smoother.
https://github.com/cotes2020/jekyll-theme-chirpy/assets/11371340/a4b22225-f097-4aa4-9612-501b6ed6bfdb

perf(ui): render background color before loading preview image

---

_posts/2019-08-08-write-a-new-post.md

1. Add docs for block math and inline math
2. Change a grammar mistake at line 137, the single form should be used
3. Change the comma at line 151 from Chinese to English for consistency
Some URLs related to the solutions added in doc.
- Understanding the origin of the problem from a MathJax issue [here](https://github.com/mathjax/MathJax/issues/3103#issuecomment-1750121053)
- [Docs](https://kramdown.gettalong.org/syntax.html#math-blocks) specifying the math block syntax used by kramdown
- [Experiments](https://zhengyuan-public.github.io/posts/PersonalBlogWithJekyll/#latex-math-equations-in-jekyll) that showed the default kramdown syntax is not working as expected and solutions that work with [jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy)

Add more contents in Mathematics and fix some typo

---

_data/locales/ru-RU.yml

Update Russian localization 
For future improvements to Russian locale, we need third and fourth form in additional to "singular" and "plural"
IDK how to explain it to a person who doesn't know Russian, but I have example :D
post = пост [singular]
posts = посты [plural]
1 post = 1 пост [singular]
2 posts = 2 поста [3rd]
3 posts = 3 поста [3rd]
...
5 posts = 5 постов [4th]
6 posts = 6 постов [4th]
...
100 posts = 100 постов [4th]
101 posts = 101 пост [singular]
102 posts = 102 поста [3rd]

Update Russian locale

---

_sass/addon/commons.scss

fix(home): crop the preview image that doesn't match 1.91:1

---

_includes/embed/twitch.html

The property of lazy load is missing in #1267

fix: resume lazy loading for Twitch videos

---

_data/share.yml
_includes/post-sharing.html
_sass/colors/typography-light.scss
_sass/layout/post.scss

This PR adds a "share to Mastodon" button as a link sharing option using @justinribeiro's share-to-mastodon package ([GitHub](https://github.com/justinribeiro/share-to-mastodon) and [NPM](https://www.npmjs.com/package/@justinribeiro/share-to-mastodon)).  I made a best guess at the correct CSS color variables to use and it seems to look alright.
- Example usage was added to `_data/share.yml`
- Liquid tags reworked slightly in `_includes/post-sharing.html` to only add the button if it was selected as an option
Discussion of proposed change - <https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1324>
Example site w/ change in place - <https://some-natalie.dev/>

Add Mastodon sharing link

---

_layouts/post.html

The url field from `authors.yml` is optional, so no link should be build when the url is empty or not defined. Previously, an empty `HREF` was generated, which is flagged as an error by html-proofer.
This change carefully controls white-space, so existing sites with defined `author.url` will be identical.
Fixes #1403

fix: url-less authors should not have empty links

---

.github/workflows/ci.yml
.github/workflows/pages-deploy.yml.hook

Jekyll's dependency [`protobuf`](https://github.com/protocolbuffers/protobuf)  is not yet compatible with Ruby 3.3. Until it releases a new version, limit the Chirpy project CI/CD to ruby versions 3.0 to 3.2. 
Resolves #1429

build(deps): specify the minor version number of ruby

---

.github/workflows/stale.yml

Add new exemption labels for stale:
- `planning`
- `in progress`
Nah

build(workflow): add more stale exemption labels

---

_sass/addon/commons.scss

Fix image left / right position breaking the structure of its subsequent prompts / quote-blocks. But for technical reasons, do not change the problem of overlapping edges of existing float images and list marker.
If for some special reason it is necessary to use a list after a float image, then we can add a Bootstrap class to the image to avoid the overlapping list marker. For instance, add  `pe-3` to the left-float image:
```markdown
- Entry a
- Entry b
- Entry c
```
- Fixes #1441

fix: image float breaks quotes and prompts

---

_includes/update-list.html

Improve the "Recently Updated" list to include the most recent (only one Git commit) posts.
This change has two benefits:
1. The post update list is consistent with the Git commit timeline.
2. Avoid users not having a list of updates to show when they first publish a site.
- #800

perf: include the latest posts in the "Recently Updated" list

---

_config.yml
_includes/head.html
_includes/img-url.html
_includes/refactor-content.html
_includes/sidebar.html

- Add configuration field `social_preview_image` that sets the site-wide default social preview image.  
For pages that do not have `page.image` set in font matter, the seo tag will use the image specified by `site.social_preview_image` as the Open Graph image.
- Refactored the generation of image URLs to reduce redundant code and enhance fault tolerance for missing or repeated slash `/` when defining image paths.
- Resolves #1452

feat: add site-wide social preview image settings

---

_includes/head.html
_includes/img-url.html

- `_includes/head.html` -  The editor's _Find and Replace_ changed the names of two variables incorrectly
- `_includes/img-url.html` - `site.img_cdn` CORS judgment condition is missing
- Fixes #1467 
- Introduced by #1463

fix: `og:image` URL  is incorrect

---

_includes/footer.html
_sass/addon/commons.scss

If `site.social.links` is empty, invalid blank links will be generated in the HTML page.
- Fixes #1493

perf: allow no social links to be configured

---

_includes/topbar.html

In tablet/desktop view (screen width >= 850px), a slash `/` is missing from the end of the `tags` and `categories` link in the breadcrumbs.
For example:
<p>
</p>
Visitors will not notice any problem when the network is working properly, because the browser will correct the URL automatically.
However, this causes PWA to fail to cache the pages `tags.html` and `categories.html`, so these two pages are repeatedly fetched from the network, and when the network is disconnected PWA ServiceWorker returns no cached content.
N/A

fix: missing "/" at the end of URLs for categories and tags in breadcrumb

---

_posts/2019-08-09-getting-started.md

Changed "go the the root of your site" to "go to the root of your site".

Typo in the "Getting Started" post.

---

_includes/head.html
_includes/img-url.html

Twitter cards were not displaying correctly due to relative URL paths. The proposed changes ensure that Twitter card meta tags use absolute URLs, aligning with best practices for SEO and social media compatibility
- Fixes #1497
This pull request addresses the issue reported in [#1497](https://github.com/cotes2020/jekyll-theme-chirpy/issues/1497) where 
Key changes include:
- Updating head.html to dynamically generate absolute URLs for Twitter card images.
- Ensuring compatibility with various social media platforms through testing.
This update has been tested across multiple social platforms to ensure correct display of Twitter card images
Special thanks to @timothystewart6 for his significant contributions to testing and refining the code.

fix: correct the Twitter Card in social share preview

---

_includes/js-selector.html
_posts/2019-08-08-text-and-typography.md
_posts/2019-08-08-write-a-new-post.md

If you place your equations inside $$\begin{equation}...\end{equation}$$ you will get MathJax equation numbering. As described here: https://docs.mathjax.org/en/latest/input/tex/eqnumbers.html
BREAKING CHANGES: if you used \begin{equation} inside $$ you will get equation numbering which was not previously present.
> This is the fixed PR for https://github.com/cotes2020/jekyll-theme-chirpy/pull/1500
See https://github.com/cotes2020/jekyll-theme-chirpy/pull/1500 for discussion.

perf: enable equation numbering in MathJax

---

README.md
_config.yml
_includes/goatcounter.html
_includes/js-selector.html

This PR adds support for a privacy-friendly alternative to Google Analytics called GoatCounter (https://www.goatcounter.com). The integration is relatively simple so it should be a low-risk addition. Documentation can be found here: https://www.goatcounter.com/help/start
Additionally I've tested this implementation in my own blog and it works fine. If you have any questions or remarks I will gladly address them of course.

Add analytics support for GoatCounter

---

_includes/img-url.html

The filter (`relative_url` and `absolute_url`) that comes with Jekyll removes the `.` from the relative path. So there are occasions when it is not appropriate to use them.
- Fixes #1541

fix: correct the generation of relative resource paths

---

package.json
rollup.config.js

- @babel/plugin-proposal-class-properties was deprecated
- https://www.npmjs.com/package/@babel/plugin-proposal-class-properties
- update to use @babel/plugin-transform-class-properties instead

build(deps-dev): remove deprecated library and add new one the npm group with 1 update

---

_config.yml

I would like to pass site verification in more search engines except Google using meta tags.
Change default configuration to make it visible that multiple services could be used for verification according to [Jekyll SEO tags usage documentation](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md) as it took a while for me to figure it out, it may be useful for others to see it right away.

feat: change site verification settings

---

_config.yml

A more sensible name for the parameter set for comments: renaming `comments.active` to `comments.provider`

perf!: rename comment setting parameter

---

_includes/embed/bilibili.html
_includes/embed/video.html
_includes/embed/youtube.html
_posts/2019-08-08-write-a-new-post.md
_sass/addon/commons.scss

I want to embed a video file hosted on my own blog, CDN, or publicly available without a video platform using the HTML 5 `<video>` element.
Here are examples on how you can include video file with respect to `img_cdn` and `img_path` variables.
```html
{% include embed/video.html
src='https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a7/How_to_make_video.webm/How_to_make_video.webm.720p.vp9.webm'
autoplay=true
loop=true
muted=true
title='How to make video' %}
{% include embed/video.html src='demo.mp4' autoplay=true loop=true title='Demo video' %}
```
Arguments:
- `src` - required, path to a file
- `poster='/path/to/poster.png'` - optional, poster image for a video that is shown while video is downloading
- `title='Text'` - optional, title for a video that appears below the video …

feat: add support for embed video files

---

_sass/addon/commons.scss
_sass/colors/typography-dark.scss

Horizontal rule is barely visible on dark theme, but has good contrast on light theme.
**Before fix:**
**After fix:**
**Root cause:** from the [beginning](https://github.com/cotes2020/jekyll-theme-chirpy/commit/b7266aceace24f21e360fd68b308269f67e655da#diff-5d99ff0381ab34cb79b58aaaa1d7f15464055e1f382085dad91272f93b61db90R90).

perf: improve `<hr>` visibility in dark mode

---

_includes/img-url.html

Correct `site.base_url` to `site.baseurl`
#1553 introduced

fix: correct the base URL parameter name

---

_includes/analytics/goatcounter.html

Explicit GoatCounter URL was changed to a protocol-relative URL while doing refactoring #1543 which causes issues.
```
Run bundle exec htmlproofer _site \
Running 3 checks (Scripts, Links, Images) in ["_site"] on *.html files...
Checking [18](https://github.com/kungfux/kungfux.github.io/actions/runs/8101471704/job/22141725592#step:6:19)0 internal links
Checking internal link hashes in [19](https://github.com/kungfux/kungfux.github.io/actions/runs/8101471704/job/22141725592#step:6:20) files
Ran on 88 files!
For the Scripts check, the following failures were found:
* At _site/404.html:1:
script link //gc.zgo.at/count.js is a protocol-relative URL, use explicit https:// instead
* At _site/about/index.html:51:
script link //gc.zgo.at/count.js is a protocol-relative URL, use explicit https:// …
```

refactor: use explicit url for goatcounter

---

_includes/embed/video.html

Incorrect variable is being used for an embeded video file alternate URL.
```
Run bundle exec htmlproofer _site \
Running 3 checks (Scripts, Links, Images) in ["_site"] on *.html files...
Checking 1[8](https://github.com/kungfux/kungfux.github.io/actions/runs/8101279120/job/22141127637#step:6:9)0 internal links
Checking internal link hashes in 1[9](https://github.com/kungfux/kungfux.github.io/actions/runs/8101279120/job/22141127637#step:6:10) files
Ran on 88 files!
For the Links check, the following failures were found:
* At _site/posts/streaming-api-and-how-to-stop-data-flow-to-test-it/index.html:[10](https://github.com/kungfux/kungfux.github.io/actions/runs/8101279120/job/22141127637#step:6:11)6:
'a' tag is missing a reference
```
This is not released yet and introduced by #1558

refactor: change alternate url for embed video file

---

_layouts/default.html

Missing pass parameter `site.lang` leads to null search result.
- Fixes #1582

fix: search result prompt is empty

---

_includes/js-selector.html
_includes/lang.html
_layouts/default.html

Allow `lang` on page/post to override `site.lang`.
This is useful to create folders (collections) of different languages. For example, I have folders `_en`, `_ru` and `_tr` (relative urls `en`, `ru` and `tr`), and then define these as collections in `_config.xml`:
```yaml
collections:
en:
output: true
ru:
output: true
tr:
output: true
defaults:
- scope:
path: ""
type: en
values:
lang: en
- scope:
path: ""
type: tr
values:
lang: tr-TR
- scope:
path: ""
type: ru
values:
lang: ru-RU
```
It's also possible to just put `lang: ru-RU` directly into the page front matter.
I removed usage of `site.alt_lang` in the `html lang` tag of `default` layout because I'm not sure what that was for. If there's a reason for it then I could put it back.
I don't exactly know what `js-selector.html` is doing …

feat(i18n): allow `page.lang` to override `site.lang`

---

_data/origin/cors.yml
_includes/js-selector.html

`jekyll-theme-chirpy` loads polyfill from `polyfill.io` for MathJax. The PR replaces `polyfill.io` w/ `cdnjs.cloudflare.com/polyfill`.
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since …

refactor: replace `polyfill.io` for `cdnjs` hosted link

---

_data/origin/cors.yml
_includes/post-description.html
_includes/related-posts.html
_layouts/home.html
_layouts/post.html
_posts/2019-08-08-text-and-typography.md
_posts/2019-08-08-write-a-new-post.md
_posts/2019-08-09-getting-started.md
_posts/2019-08-11-customize-the-favicon.md
_sass/layout/post.scss
assets/feed.xml

I would like to have control over the post summary that appears on the `Home` page, in the `Further Reading` section, and in the RSS feed instead of the auto-generated one that is not always great for this purpose.
ref #1596
ref #1516 
A similar feature `summary` already exists and is used for RSS feed summary exclusively. However, it's support is removed with this PR and replaced by `description`.
- Homepage
- Posts page

feat: make post description customizable

---

_includes/footer.html

Summary: Display theme version.
Motivation: When I'm working on my blog, I like to see the current version of the theme I'm using.
- It's helpful to see which version we use, it helps to avoid unnecessary steps to find the theme version.
- It also makes it easier to write reports, as users can see the version they have a problem with right away. Especially if the user specifies theme like this: ">= 5.6".

feat(footer): display theme version

---

_data/share.yml

"Test Site" fails when Weibo sharing is enabled.
like [this](https://github.com/long-910/long-910.github.io/actions/runs/8309620866/job/22741192309)
```
http://service.weibo.com/share/share.php?title=XXX&url=YYY is not an HTTPS link
```

fix:  use `https` for Weibo sharing URL

---

_config.yml
_includes/comments/giscus.html

I noticed that `giscus`'s `data-strict` option isn't being set, and can't be configured.
This may be a newer option that wasn't available when it was initially introduced.
Either way it's a pretty straight-forward change to add support and a default value.
_[giscus.app](https://giscus.app/)_

feat: add support for giscus strict title matching

---

_includes/head.html

**Problem**: I have noticed that social image preview is not always being displayed for Twitter and people reporting the same in #1599.
**Solution**: Follow Twitter [guidelines](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started) for `meta` tags naming when we replace generated one by Jekyll.
I'm using [extension](https://chromewebstore.google.com/detail/social-share-preview/ggnikicjfklimmffbkhknndafpdlabib) to test these changes, but I assume the solution was tested in #1599.

fix: correct the attribute for the Twitter social image

---

_includes/img-url.html

When a cross-domain `site.img_cdn` is set and the default site-wide social graph URL (`site.social_preview_image`) is a local path, the URL of the social preview image inside the SEO tag is incorrect.
```yaml
img_cdn: https://chirpy.cotes.page
social_preview_image: /commons/devices-mockup.png
```
```html
<meta property="og:image" content="https://chirpy.cotes.pagehttps://chirpy.cotes.page/commons/devices-mockup.png">
<meta property="twitter:image" content="https://chirpy.cotes.pagehttps://chirpy-img.netlify.app/commons/devices-mockup.png">
```
This PR corrects the logic of `_includes/img-url.html` to fix the above issue.

fix(seo): correct social preview image path inside `<meta>` tag

---

_includes/comments.html

I can't see the comments, because
In #1563, the parameter name of the comment has been changed from `active` to `provider`, but the change was not applied to `comments switcher`.
https://github.com/cotes2020/jekyll-theme-chirpy/pull/1563

Fix references to comment parameter `site.comments.provider`

---

_config.yml
_includes/embed/audio.html
_includes/embed/video.html
_includes/head.html
_includes/media-url.html
_includes/refactor-content.html
_includes/sidebar.html
_layouts/home.html
_posts/2019-08-08-write-a-new-post.md
_posts/2019-08-09-getting-started.md
assets/js/data/swconf.js
tools/init
tools/release

We discussed the variable changes in [this PR](https://github.com/cotes2020/jekyll-theme-chirpy/pull/1618#discussion_r1548704447).

refactor: rename img-url to media-url and site.img_cdn to site.cdn

---

_includes/js-selector.html
_posts/2019-08-08-write-a-new-post.md
assets/js/data/mathjax.js

Move `MathJax` configuration to file `assets/js/data/mathjax.js` will help add extensions.
- #1663

feat(deps): move `MathJax` configuration to a separate file

---

.github/workflows/cd.yml
.github/workflows/publish.yml
docs/CHANGELOG.md
package.json
tools/release

[`standard-version`](https://github.com/conventional-changelog/standard-version/) has been deprecated since May 2022, so it is necessary to stop using it for this project. 
[**`semantic-release`**](https://github.com/semantic-release/semantic-release) is available as a more capable alternative to help automate the release process:
1. Updating Node/Gem version numbers
2. Generating changelogs
3. Automating GitHub Releases
4. Building Chirpy-gem and pushing it to RubyGems.org
5. Create commits and tags on the `production` branch
6. Merge the `production` branch into the `master` branch
> ⚠️ Note: Step _6_ may be canceled in CD environments due to merge conflicts, so we need to do this step manually in such cases.
Whenever a commit is pushed to the release branch (`production`), all of the …

ci(release): replace `standard-version` with `semantic-release`

---

_includes/sidebar.html
_sass/addon/commons.scss

The Tab key focus
This bug was first fixed in #453, but a later refactoring that upgraded to _Bootstrap 5_ caused the issue to resurface.
This change fixes the above issue against the BS5 update.
- See also #453

Outline the mode-toggle when it receives keyboard focus

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/starter/pages-deploy.yml

Ruby 3.0 ended on 2024-03-31. 
See: <https://www.ruby-lang.org/en/downloads/branches/>

Drop Ruby 3.0 and introduce Ruby 3.3

---

.github/workflows/ci.yml
.github/workflows/style-lint.yml

The default version of the node in `actions/setup-node@v4` is `v18.20.2`, which is lower than the requirement of the dependency package ( >= `v20.8.1`)
See the section "Build Assets"  in <https://github.com/cotes2020/jekyll-theme-chirpy/actions/runs/8713275846/job/23901361027>
<details>
<summary>Build Assets</summary>
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'semantic-release@23.0.8',
npm WARN EBADENGINE   required: { node: '>=20.8.1' },
npm WARN EBADENGINE   current: { node: 'v18.20.1', npm: '10.[5](https://github.com/cotes2020/jekyll-theme-chirpy/actions/runs/8713275846/job/23901361027#step:5:6).0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@semantic-release/commit-analyzer@12.0.0',
npm WARN …
```

Specify the node version

---

_includes/related-posts.html

I modified the code in `_includes/related-posts.html` to enable **Further Reading** to display the latest posts, as stated in the title.
I need to explain why I made this change. 
Consider a scenario where we have five different posts, e.g.
```
_posts
├─ Title1.md
├─ Title2.md
├─ Title3.md
├─ Title4.md
└─ Title5.md
```
each of which has the **same score** calculated in `_includes/related-posts.html`. When we open any of these posts, Further Reading always displays the three oldest posts instead of the three most recently updated ones. 
As an example, when we open `Title4` post, It shows `Title1`, `Title2` and `Title3`,
The same is true when opening `Title5`. No matter how many posts we write later, it will always display only the first 3 posts.
We might prefer it to show the latest 3 …

refactor: make Further Reading display the latest posts.

---

_includes/toc.html
_javascript/modules/components/toc.js

When internet connection speeds are poor, there is a chance that the title of the TOC will appear earlier than its entries, causing a visual cutoff.

Make TOC title and its entries visible at the same time

---

assets/js/pwa/sw.js

I'm going to try to solve an issue related to caching files that are chunked for transfer (usually they have a 206 status) that we have discussed here GH-1651. To avoid this error, we should only cache files that have a response code of 200.

fix(pwa): avoid caching large files

---

_config.yml

The footnote back arrow will become emoji on IOS, see the following figure,
This problem is not caused by Jekyll, but by Kramdown and Apple, see [Kramdown](https://kramdown.gettalong.org/quickref.html#fnref:1) and [Jekyll](https://github.com/jekyll/jekyll/issues/3751) and [here](https://bendodson.com/weblog/2016/01/11/fixing-emoji-footnote-arrow-in-jekyll/#fn:kramdown).
Just add the following code to `_config.yml` can fix this problem:
```yml
kramdown:
footnote_backlink: "&#8617;&#xfe0e;"
```
where `&#xfe0e;` is text presentation selector, used to request a text presentation for an emoji character, see [Unicode](https://www.unicode.org/reports/tr51/#def_text_presentation_selector).
You can see the following [examples](https://www.ii.com/unicode-variation-selectors-15-16/#_table_of_variatio …

fix: prevent footnote back arrow from becoming an emoji on IOS

---

_data/origin/cors.yml
_includes/head.html
assets/js/data/swconf.js
assets/js/pwa/sw.js

Improved the data structure for defining resource hints to the browser.
N/A

Optimize the resource hints

---

_data/origin/basic.yml
_data/origin/cors.yml
_includes/js-selector.html
_javascript/modules/components/category-collapse.js
_javascript/modules/components/clipboard.js
_javascript/modules/components/tooltip-loader.js
_javascript/pwa/_frontmatter
_javascript/pwa/app.js
_javascript/pwa/sw.js
package.json
rollup.config.js

Importing the required Bootstrap JS accurately reduces the time taken to load the web page for the first time. It also reduces the size of browser storage used by PWA.
Additionally, the JavaScripts that work with PWA are again compiled by `rollup`, as I found a perfect way to make `sw.js`export to the root of the site even after installing it through Jekyll runtime.
- 6b34901d94d7c9332accae7ab907ba77c4e247a1
- #1501

Lean Bootstrap Javascript

---

_includes/embed/audio.html
_includes/embed/video.html
_posts/2019-08-08-write-a-new-post.md

Embedded video does not respect the media_subpath Front Matter variable #1738.
Root cause: #1618 (actually postponed due to possible issues fixed in #1672).
Since cache issue is fixed, it should be safe to use `media_subpath` for all media types now as it was [discussed previously](https://github.com/cotes2020/jekyll-theme-chirpy/pull/1618/files#r1548601924).
Fixes #1738

Use media_subpath for media embed

---

_includes/pageviews/goatcounter.html

The goatcounter PV report splits numbers with spaces, e.g. 1024 would be '1 024'
N/A

Goatcounter PV greater than 1K cannot be converted to numbers

---

_posts/2019-08-08-write-a-new-post.md

A redundant  ` ``` `  line left over from the last revision of the tutorial broke the markdown syntax.

Correct markdown syntax of tutorial

---

.devcontainer/devcontainer.json
.devcontainer/post-create.sh
.github/dependabot.yml
.gitignore
.vscode/extensions.json
.vscode/settings.json
README.md
tools/run.sh

Improve the experience of developing on cross-platform with vscode Dev Container.
Refer to the [VS Code docs][docs] to complete the following installation:
- Docker Engine
- Extension [Dev Containers][devcontainers]
[docs]: https://code.visualstudio.com/docs/devcontainers/tutorial#_prerequisites
[devcontainers]: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
- Ruby, Bundler and Jekyll
- NVM, NPM and Node.js
- Shell using Zsh and `Oh-My-Zsh` with Git plugin enabled.
- A set of extensions for syntax check and formatting of code.
Please use _Clone Repository in Container Volume_ to build for better disk I/O performance.
- Discussed in #1767

Add vscode devcontainer

---

.gitignore
_config.yml
_includes/js-selector.html
_javascript/_copyright
_javascript/pwa/_frontmatter
jekyll-theme-chirpy.gemspec
package.json
rollup.config.js
tools/init.sh
tools/release.sh

The `rollup-plugin-license` has been using too many deprecated dependencies, so it is necessary to remove it.
As an alternative, this changes uses Rollup `output.banner` to insert copyright information. Since `terser` runs after `output`, it is not possible to insert the Front Matter defining permlink for `sw.js` through the same way (Jekyll Front Matter is YAML rather than JS, which would cause errors with terser).
Therefore, _Jekyll Collection_ is now used to add permlink to `sw.js`, with the collection named `app`, and the directory placed in `_app`. This directory is not tracked by git, but it will be included when building the gem.

Remove package `rollup-plugin-license`

---

_sass/addon/syntax.scss
_sass/colors/syntax-dark.scss
_sass/colors/syntax-light.scss

Improved visibility of inline code in prompts and tables, especially in dark mode
N/A

Improve visibility of inline code

---

_sass/addon/commons.scss
_sass/addon/module.scss

The info prompt icon is flipped 180 degrees to visually match the letter `i`, but does not duplicate the sidebar's "About" tab icon.
Resolves:
- #1130
- #1347

feat(ui): make `info-prompt` icon looks like letter i

---

_data/contact.yml
_data/share.yml

- Add Threads (social network) sharing option
- Add Threads (social network) contact option
* Following the dynamic URL structure announced by an engineer from Threads -> https://www.threads.net/@0xjessel/post/C2isac0P7c7

feat: add Threads (social network) social links

---

.gitignore
.vscode/tasks.json

Add `tasks.json` to automate typical tasks and improve dev experience.
- When you open a project, watch task automatically starts, so you don't have to run tasks/commands manually
- Press `Ctrl+Shift+B` to run build and watch task
- Run any task from VS Code UI or command palette
Initial discussion has happened in [1781](https://github.com/cotes2020/jekyll-theme-chirpy/pull/1781#discussion_r1616431375).
[Documentation](https://go.microsoft.com/fwlink/?LinkId=733558) on tasks.

Automate build tasks

---

_javascript/pwa/sw.js
assets/js/data/swconf.js

To retrieve pageviews we send `GET` request from `_includes/pageviews/goatcounter.html`. When PWA is enabled, the response is cached and so the pageview counter is not updated as expected.
I see two possible ways to fix this behavior:
1. Make `GET` requests unique
2. Avoid caching these requests
Option 1 is easy fix, applied in this PR but has it's drawbacks e.g. utilize cache.
Option 2 seems preferable. However, it requires changes in `_javascript/pwa/sw.js` to support non-relative paths.
Please let me know your thoughts on this.

bugfix: prevent pageview requests caching

---

_javascript/modules/components/img-popup.js

Remove extra dual-mode images from lightbox

---

_javascript/modules/components/img-popup.js

Repeatedly using `GLightbox.destroy()` (>= 4 times) will cause `GLightbox` to fail to generate new objects
- #1883

refactor: improve the efficiency of `GLightbox` switching

---

_config.yml
_includes/analytics/fathom.html

Add Fathom web analytics tracking code.
- How to add embed it: https://usefathom.com/docs/script/embed
- Documentation: https://usefathom.com/features/how-fathom-analytics-works

feat(analytics): add fathom analytics

---

.gitignore
_config.yml
jekyll-theme-chirpy.gemspec
rollup.config.js
tools/init.sh
tools/release.sh

In #1796, customized Jekyll collection `app` can't be passed through the gem to the user-end.
So now output PWA JS files to the default directory `assets/js/dist`, and create a new custom `rollup` plugin to insert the Jekyll font matter for them.
- #1796

Improve the JS build for PWA

---

_includes/js-selector.html
_javascript/pwa/app.js
_javascript/pwa/sw.js
package.json
rollup.config.js

In #1734, the expected behavior of reading options from `_config.yml` in `app.js` is limited to the site configuration state at the time of the `app.js` _Rollup_ build. This means that it does not capture user-defined `baseurl` (#1909).
Therefore, this has been modified to pass the baseurl to app.js via the URL to achieve the intended design.
- Affected versions: `v7.0.0` ~ `v7.0.1`
- Fixes #1909

Fix `baseurl` not passed to `app.js`

---

_includes/sidebar.html
_sass/addon/commons.scss

I would like to eliminate the use of `<h1>`for site title in the sidebar. Ref #1907 
I am having problems with search engines indexing blog posts. I would like to make the `<h1>` tag unique for post titles.

Remove `h1` element from site title

---

_javascript/modules/components/toc/toc-mobile.js

**Problem:** Closing a popup by pressing `Esc` is not handled correctly.
**Scenario:**
- Open blog post on mobile view
- Click `Contents`
- Close popup with `Esc` key
**Expected:** Popup is closed with animation.
**Actual/Problem:** Popup is closed without animation.
- Click `Contents` again
**Expected:** Popup can be opened again.
**Actual/Problem:** Popup is being closed on open (for the first time after closing). See recording attached.
<details>
<summary>Recording</summary>
</details>
Ref #1964

fix: close popup gracefully with Esc key

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/commitlint.yml
.github/workflows/pr-filter.yml
.github/workflows/publish.yml
.github/workflows/scripts/pr-filter.js
.github/workflows/style-lint.yml

- Unchain commit-lint and CI
- Even if a commit does not meet the CI path filter, it still needs to lint the commit message.
- Unchain PR filter and CI
- The CI workflow needs to be triggered when the commits in a pull request are modified.
- Allow manual publishing
- Sometimes `semantic-release` will error out due to commit messages referencing discussions, but this does not affect the final RubyGems/GitHub Release. In such cases, manual triggering of the publish process is needed to complete the remaining publishing steps.

Improve workflow triggers

---

Gemfile

Below error occurred when running "bundle install" when using ruby 3.3.5, gem 3.5.22, gcc 14.2.0, GNU Make 4.4.1. 
"""
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Installing wdm 0.1.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
.
.
.
creating Makefile
.
.
.
make: *** [Makefile:248: rb_monitor.o] Error 1
make failed, exit code 2
.
.
.
An error occurred while installing wdm (0.1.1), and Bundler cannot continue.
In Gemfile:
wdm
"""
Fixed by installing wdm 0.2.0 using the proposed change to the gemfile.
A user will not able to run the server locally as described in the wiki when using the latest versions Ruby (v3.3.5), gem (v3.5.22), GCC (v14.2.0), and GNU Make (v4.4.1). This fix can make sure to avoid any …

fix(gemfile): update wdm gem version for compatibility

---

.github/workflows/pr-filter.yml
.github/workflows/scripts/pr-filter.js

- Checking the repository of the PR is more effective than checking the label to identify bot-initiated PRs
- This change also allows more flexible PR body definitions for developers with write access to the repository
N/A

Reduce unnecessary pr-filter runs

---

_includes/toc.html
_layouts/default.html
_sass/abstracts/_placeholders.scss
_sass/layout/_panel.scss
_sass/pages/_post.scss

This enhancement addresses an issue from years ago — the inability to vertically scroll the TOC when it exceeds the screen height in desktop mode.
- Fixes #321, #1841

Support vertical scrolling for TOC in desktop mode

---

_includes/pageviews/goatcounter.html

The pageviews script is loaded inside the `<head>` and is therefore executed too early, causing pageviews to display an infinite spinner. In Chirpy 7.1.1 the script was loaded at the end of the `<body>`.

fix: ensure pageviews are fetched after DOM is loaded

---

rollup.config.js

1. Correct the rollup watch path
2. Avoid registering watch listeners redundantly across multiple tasks
N/A

Correct the js build watch path

---

_includes/head.html

When theme is forcibly set, the theme script is excluded, which causes multiple problems. Fixes #2066

fix: always load theme script

---

_includes/toc.html
_sass/pages/_post.scss

Fix on UI: In desktop mode, H2 and the first sub-level H3 in the TOC are too close.

Adjust the gap between TOC entries

---

_sass/pages/_post.scss

In desktop mode, the randomness of the script execution order in the browser may cause the fade-up animation of the TOC to be lost.
https://github.com/user-attachments/assets/291c9fdc-cdca-491f-b9b0-dcc619c77af1

Keep TOC fade up in desktop mode

---

_includes/toc.html
_sass/pages/_post.scss

fix(ui): left borderline of TOC is notched

---

_includes/toc.html
_javascript/modules/components/toc.js
_javascript/modules/components/toc/toc-desktop.js
_posts/2019-08-08-write-a-new-post.md
_sass/pages/_post.scss

The latest patch for version `7.2.0`:
* fix: toc not visible when switching from mobile to desktop mode (#2139)
* docs: update the setting name for the comments
* fix(ui): left borderline of TOC is notched (#2140)

Release v7.2.4

---

_data/locales/fa-IR.yaml

This PR adds Persian (Farsi) language support to the `jekyll-theme-chirpy`. The translation includes:
- Common labels (e.g., posts, categories, tags)
- Sidebar tabs (e.g., home, categories, tags, archives, about)
- Search bar and results text
- Panel labels (e.g., last modified, trending tags, table of contents)
- Copyright and license information
- Meta descriptions
- 404 error page text
- Post-related labels (e.g., written by, posted, updated, words, page views, read time, share buttons)
- Date and time formats
- Categories page labels
The translation ensures that Persian-speaking users can navigate and interact with the theme seamlessly.
This addition does not introduce any breaking changes and is fully compatible with existing functionality. The Persian language can be activated by …

Add Persian Language Support to Jekyll-Theme-Chirpy

---

_posts/2019-08-08-write-a-new-post.md

Sorry for this tiny nitpick PR... it just fixes the spelling of "category" in the post that I couldn't unsee.
If "categorie" was supposed to reflect the Dutch, Italian, or Romanian spelling, please disregard this.  :)
https://en.wiktionary.org/wiki/categorie

Fix typo in 2019-08-08-write-a-new-post.md

---

_data/locales/ja-JP.yml

This is the first version of `ja-JP.yml`.
'01 / 23' is preferred over '23 / 01,' '23 Jan,' or 'Jan 23' in Japan.
But, it is difficult because the date is hard coded.
Workaround: Copy [`_layouts/archives.html`](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_layouts/archives.html) into your repository's `_layouts` and change the hard coded date (line 26-29):
```html
<span class="date day" data-ts="{{ ts }}" data-df="DD">{{ post.date | date: '%d' }}</span>
<span class="date month small text-muted ms-1" data-ts="{{ ts }}" data-df="{{ df_dayjs_m }}">
{{ post.date | date: df_strftime_m }}
</span>
```
⬇️
```html
<span class="date day" data-ts="{{ ts }}" data-df="MM /">{{ post.date | date: '%m /' }}</span>
<span class="date month small text-muted ms-1" data-ts="{{ ts }}" …
```

Add ja-JP.yml

---

_includes/topbar.html

This PR fixes a visual glitch where the top bar would shrink by a few pixels when using the search bar.
Fixes #2337

fix(search): fix visual glitch causing top bar to shrink during search

---

_data/locales/ca-ES.yml

Added Catalan Spanish locale translation v1.0.
Catalan and Spanish are distinct languages. While they share similarities as Romance languages and coexist in regions like Catalonia and Valencia, they are not the same. This translation should be evaluated solely as Catalan.
No dependencies
Fixes #1931

Add new enhancement ca es

---

_javascript/modules/theme.js

The `theme.js` does not include the recognition of the global theme mode in the site configuration, which may cause initialization errors for other plugins that depend on the theme mode, such as `giscus`.
- Fixes #2356

fix: recognize global theme mode

---

_sass/abstracts/_placeholders.scss
_sass/pages/_post.scss

This PR fixes a tiny visual imperfection when hovering over a tag.
[Screencast_20250417_005006.webm](https://github.com/user-attachments/assets/11cebbf1-fd4a-4cfa-b469-11190e6c5693)
I probably have some kind of OCD 😄

fix(css): prevent tags resizing on hover

---

_includes/refactor-content.html

Improve accuracy of moving `img` element classes
