_layouts/home.html, assets/css/_addon/syntax.scss
=> typo fix: s/defualt/default/

.github/workflows/ci.yml, .github/workflows/pages-deploy.yml.hook, _scripts/sh/create_pages.sh
`sed` has its limitation when processing structured data. Introducing `yq` to extract `tags` and `categories` is more robust.
A concrete case I had to deal with is YAML array defined in the format of:
```
tags:
- foo
- baar
- 42
```
The downside is pretty clear that users will need to install yet another tool. So please free feel to reshape this PR or reject it.
- Browerser type & version: Chrome version 85.0.4183.102 (Official Build) (64-bit)
- Operating system: Ubuntu 20.04 kernel 5.4.0-47-generic
- Bundler version: Bundler version 2.1.4
- Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
- Jekyll version: jekyll 4.1.1
=> Use yq to process YAML content

README.md
Short update to correct a typing error on README file
e.g. Fixes #(issue)
- N/A
=> Update typing error

.github/PULL_REQUEST_TEMPLATE.md
Just a small typo fix. Browerser -> Browser
e.g. Fixes #(issue)
Not relevant for this small of a change
- Browerser type & version: Not relevant
- Operating system: Not relevant
- Bundler version: Not relevant
- Ruby version: Not relevant
- Jekyll version: Not relevant
=> Small typo fix

_data/locales/id-ID.yml
Adding Translation for Indonesian Language File.
=> Add Indonesian translation & locales

_data/locales/en.yml, _data/locales/id-ID.yml, _includes/search-loader.html
Hope i can help contributing to this awesome project. I'm new to GitHub but i just wan't to help you out!
=> Add search 'not found' Indonesian translation

_data/locales/ru-RU.yml, _data/locales/uk-UA.yml
Added Russian and Ukrainian translation and locales
=> Added Russian and Ukrainian translation and locales

_data/locales/vi-VN.yml
Add Vietnamese locale.
- Browser type & version: Chrome 98.0.4758.102
- Ruby version: 3.0.3p157 
- Bundler version: 2.3.7 
=> Add Vietnamese locale

_data/locales/es-ES.yml
=> feat: add es-ES support to locales

_includes/post-nav.html, _includes/post-paginator.html, _includes/refactor-content.html, _includes/sidebar.html
Some fixes for invalid HTML (using https://validator.w3.org/ to check), pagination fix when using a different path config and fix hidden posts still showing in archives.
- Browser type & version: Firefox 98.0.2
- Ruby version: 2.7.4p191
- Bundler version: 2.3.8
- Jekyll version:  4.2.1
=> Fix various

_data/locales/fr-FR.yml
Add local file for amazing french peoples :star2: (use fr-FR to include it into _config file)
- Operating system: GitHub
- Ruby version:  ruby 3.1.2p20 
- Bundler version:  2.3.14
- Jekyll version:  4.2.2
=>  feat: add fr-FR support to locales (#582) 

_data/locales/hu-HU.yml
Adding Translation for Hungarian Language File.
=> Added Hungarian translation and locales

_data/locales/bg-BG.yml
Bulgarian language and locale added.
- Browser type & version: Brave 1.39.122
- Operating system: Windows
=> Added: Bulgarian Language

_data/locales/de-DE.yml
Added de-DE.yml for german translations.
- Ruby version: 3.1.2p20
- Bundler version: 2.3.7
=> Added german locale file

_posts/2019-08-09-getting-started.md
=> Fix a typo

_data/locales/cs-CZ.yml
=> feat(i18n) add Czech language

_data/locales/fi-FI.yml
Added Finnish yml file whit translations
Added fi.FI.yml file with Finnish translations
- [ x] New feature (non-breaking change which adds functionality)
I have tested this in my own blog that has non been released yet. 
- [x ] I have tested this feature in the browser
- Jekyll version: 
- [ x] I have performed a self-review of my code
- [ x] I have commented on my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
=> Created fi-FI.yml

.github/workflows/pages-deploy.yml.hook
To alleviate these warnings (this older action [will stop working on May 31](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
Build with `@v3` works as expected: https://github.com/joshjohanning/joshjohanning.github.io/actions/runs/4427107893
n/a
=> chore: update configure-pages action

_data/locales/sl-SI.yml
I've add new file with slovenian translations. 
Also thank you for your work on your amazing theme. 
- [] I have tested this feature in the browser
=> feat: added sl-SI.yml with slovenian translations

.github/PULL_REQUEST_TEMPLATE.md
Reduce unnecessary filling requirements to reduce PR creation time.
Previewed with a Markdown editor
=> chore(docs): simplify github PR template

_includes/update-list.html, _sass/addon/commons.scss
=> Fix text truncation in "Updated List"

_sass/addon/commons.scss, _sass/addon/syntax.scss, _sass/layout/archives.scss, _sass/layout/category-tag.scss, _sass/layout/home.scss, _sass/layout/post.scss
See: https://stylelint.io/user-guide/rules/media-feature-range-notation/
=> style(scss): fix style-lint `media-feature-range-notation` issue

.github/stale.yml
The stale app is deprecated and  no longer maintained
=> build: replace the stale app with gh-actions

_data/locales/th.yml
This pull request adds a Thai translation file, `th.yml`.
=> feat(i18n): add Thai locale file

_includes/head.html, _includes/search-results.html, _layouts/default.html, _layouts/page.html, _layouts/tags.html, jekyll-theme-chirpy.gemspec
Resolves #1094
Improvements to: 
- #1097
=> perf(build): use `jekyll-include-cache` plugin to reduce build time

tools/init, tools/release, tools/test
Changed the help examples of commands echoed by each method.
=> Chore: Remove .sh from executable names in each help method

_includes/post-paginator.html, _layouts/category.html, _layouts/home.html, _layouts/page.html, _layouts/tag.html, _layouts/tags.html, _sass/addon/commons.scss
=> Improve margin bottom of the core block

CHANGELOG.md, _sass/jekyll-theme-chirpy.scss, jekyll-theme-chirpy.gemspec, package.json, tools/release
=> Release 6.1.0

_config.yml
This PR changes the comment in the _config.yml file to link to a [properly working, modern timezone picker](https://kevinnovak.github.io/Time-Zone-Picker)
=> docs: Change timezone picker to modern, working alternative

_data/locales/tr-TR.yml
Updated Turkish Language
No need. only strings changed.
=> Updated Turkish Language

_data/contact.yml, _data/share.yml, _includes/post-sharing.html, _sass/layout/post.scss
Updated the Twitter brand icon to a 'X'
=> Update the Twitter icon

_includes/comments/utterances.html
This issue exists since Chirpy `v6.0.0`
- Fixes #1232
=> Fix `utterances` initialization failure 

_layouts/page.html
The layout `page` missing the `lang` specification
=> Fix code snippet clipboard tooltip missing title

_includes/comments/giscus.html
Enable the `giscus` lazy loading option to improve web performance.
=> Lazy load the `giscus` comments

_posts/2019-08-09-getting-started.md
After this change, the corresponding post (2019-08-09-getting-started.md) must also be adjusted.
https://github.com/cotes2020/jekyll-theme-chirpy/commit/806fa3aa1a7444186e1db4fe693886450e351997
Nothing else...
=> fix(posts): change stylesheet name in post. (2019-08-09-getting-started.md)

_data/locales/de-DE.yml
* Add common German date format.
* Fix translation of read time prompt to a more correct word.
* Add common German date formats.
* Fix translation of read time prompt to a more correct word.
Read time unit needs a singular and plural version to be correctly translated.
=> German language localisation

assets/js/pwa/sw.js
Hiding the time zone of the build machine enhances privacy protection.
=> Enhance PWA cache privacy protection

_sass/addon/commons.scss, _sass/addon/module.scss, _sass/colors/typography-dark.scss, _sass/colors/typography-light.scss, _sass/layout/post.scss
Standardize metadata text styles and remove some outdated code.
N/A
=> Standardize metadata text styles

_data/origin/cors.yml
- Updates `bootstrap` to 5.3.2
- Updates `dayjs` to 1.11.10
- https://github.com/cotes2020/chirpy-static-assets/pull/10
=> Update dependent libraries

_includes/embed/bilibili.html, _posts/2019-08-08-write-a-new-post.md, _sass/addon/commons.scss
Add embed bilibili video template in `_includes/embed/bilibili.html` like YouTube or twitch
=> Add bilibili support

_sass/addon/commons.scss
- Undo changes in #1449
- Close #1477
=> fix: resume the `blockquote` display type

tools/release
The gem should be built on the `production` branch.
- Fixes #1569
=> build(release): build the gem on the `production` branch

_includes/img-url.html
=> Correct the creation of image URLs for posts

.github/workflows/codeql.yml, .github/workflows/style-lint.yml
The _Pull Request_ triggers `style-lint` and `CodeQL` to run twice each, and this change avoids that redundant workflow.
N/A
=> ci: reduce duplicate actions

_data/origin/basic.yml, _data/origin/cors.yml, _includes/comments/disqus.html, _includes/comments/giscus.html, _includes/comments/utterances.html, _includes/head.html, _includes/js-selector.html, _includes/mermaid.html, _includes/sidebar.html, _includes/topbar.html, _javascript/modules/components/back-to-top.js, _javascript/modules/components/category-collapse.js, _javascript/modules/components/clipboard.js, _javascript/modules/components/img-loading.js, _javascript/modules/components/img-popup.js, _javascript/modules/components/locale-datetime.js, _javascript/modules/components/mode-watcher.js, _javascript/modules/components/search-display.js, _javascript/modules/components/sidebar.js, _sass/addon/commons.scss, assets/js/pwa/app.js
Dropped `jQuery`, also replaced `magnific-popup` with `GLightbox`
N/A
=> perf: replace jQuery with Vanilla JS

_includes/mode-toggle.html
Reduce conditional logic to speed up theme mode initialization and switching.
N/A
=> Simplify mode toggle script

_config.yml, _includes/analytics/cloudflare.html
Add Cloudflare web analytics tracking code
- Demo: https://blog.cloudflare.com/privacy-first-web-analytics
- Documentation: https://developers.cloudflare.com/analytics/web-analytics
- Example tracking code: https://developers.cloudflare.com/analytics/faq/web-analytics/#can-i-add-web-analytics-to-my-site-using-a-tag-manager-like-google-tag-manager-gtm
Refer to [Enabling Cloudflare Web Analytics](https://developers.cloudflare.com/analytics/web-analytics/getting-started) for where to find the CWA token.
=> Add Cloudflare Web Analytics

_includes/comments/giscus.html
=> Adapt the giscus localization parameter

_data/contact.yml, _data/share.yml
- Add Reddit sharing option
- Add Reddit contact option
N/A
=> feat: add Reddit social links

_posts/2019-08-09-getting-started.md
docs: add devcontainers tutorial
- Documentation for #1781
=> Add Dev Containers tutorial

Gemfile, _sass/addon/commons.scss, _sass/addon/syntax.scss, _sass/colors/typography-dark.scss, _sass/colors/typography-light.scss
When updating Gem files and such, depreciation warnings show up, one about Sass and SCSS nesting.
This aims to mitigate those warnings by arranging the code, as well as add missing `gem`'s to the **Gemfile**, without would show up as warnings because of depreciations.
=> Update to reduce warnings/depreciations

_sass/addon/commons.scss, _sass/addon/module.scss, _sass/addon/syntax.scss, _sass/addon/variables.scss, _sass/layout/categories.scss, _sass/layout/home.scss, _sass/layout/post.scss
Impact:
- Increase the border radius of inline code and `<kbd>` tags
- Variable `$base-radius` renamed to `$radius-lg`
=> refactor(ui): standardize the border radius

_layouts/home.html
Fix the issue described in #1959 
Close #1959
=> Fix pagination error

_data/locales/hu-HU.yml
Hungarian language updated with the date format, the categories page and a few semantic additions.
=> feat(i18n): update hungarian translation

.github/workflows/pr-filter.yml, .github/workflows/scripts/pr-filter.js
To filter out a large number of blank PRs unintentionally created by new contributors, a new workflow has been created. PRs that do not follow the template will also be closed due to incomplete information, but it identifies whether a PR is created by @dependabot based on its labels.
=> Auto block invalid pull request

.github/workflows/ci.yml, .github/workflows/commitlint.yml, .github/workflows/pr-filter.yml, .github/workflows/scripts/pr-filter.js
Chain CI and Commit-Lint together
Reduce the frequency of CI workflow runs and additionally chaining CI and Commit-Lint together.
Enhancements to #2010
=> Skip test for invalid PRs

assets/feed.xml
Add content attribute type to improve interoperability according to the [Feed validation service](https://validator.w3.org/feed/check.cgi) suggestion:
> This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
>
> [line 1](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fchirpy.cotes.page%2Ffeed.xml#l1), column 1042: Missing content attribute: type (4 occurrences) [[help](https://validator.w3.org/feed/docs/warning/MissingTypeAttr.html)]
>
> ... .page/posts/customize-the-favicon/</id> <content src="https://chirpy.cot ...
Reference #982 by @twhite96
=> chore: improve feed interoperability

_config.yml
=> Exclude `purgecss.js` from output files

_data/locales/nl-NL.yml
Added nl-NL.yml for dutch translations.
=> add Dutch Locale

_config.yml
=> JS files in subdirectories are excluded from the site output

_javascript/modules/components/toc.js, _javascript/modules/components/toc/toc-desktop.js
=> Fix toc not visible when switching from mobile to desktop mode

_posts/2019-08-09-getting-started.md
Corrects the shell command for starting the Jekyll server locally. 
For someone new to Jekyll, this correction prevents some confusion and makes the help post more useful.
=> Corrects command in help post to start Jekyll server locally

_data/locales/da-DK.yml
I saw the update 7.3.0 added functionality for new languages. I saw Danish was missing and have therefore created it.
Hope you will use it in next update :-)
_None_
=> i18n: Added Danish locale
